 package com.abuye.core.jdbc.resource;
 
 import java.util.ListResourceBundle;
 
 public class ExceptionInfo_zh_CN extends ListResourceBundle
 {
   private static final Object[][] exceptionInfoContents = { 
     { "common.sQLExceptionCode", "SQLException异常的编码：" }, 
     { "common.sQLStatusCode", "，错误状态码：" }, 
     { "common.sQLExceptionAdviceInfo", 
     "，请查询所用的JDBC驱动程序相关的技术参考文档可以了解详细的错误原因。原始的异常错误信息如下：" }, 
     { "common.notCloseJDBCConnection", 
     "不能关闭JDBC数据库连接对象" }, 
     { "common.orignalSQLExceptionInfo", 
     "原始的异常错误信息如下：" }, 
     { "jdbcConnection.noJDBCConnection", 
     "不能正确地获得JDBC数据库连接对象，可能是数据库服务器没有启动或者数据库连接的工作参数设置不正确。" }, 
     { "jdbcConnection.noJDBCConnectionAndCheck", 
     "不能正确地获得JDBC数据库连接对象，可能是数据库服务器没有启动或者数据库连接的工作参数设置不正确。请检查相关的数据库连接参数。" }, 
     { "jdbcConnection.noCallableStatement", 
     "不能正确地创建出调用存储过程的CallableStatement语句对象，可能是所要调用的存储过程不存在或者所给定的存储过程的名称不正确。请检查存储过程：" }, 
     { "jdbcConnection.callableStatement.parameterError", 
     "不能正确地设置存储过程所需要的输入调用参数，可能是参数的类型不正确或者参数的个数不一致。请检查存储过程：" }, 
     { "jdbcConnection.callableStatement.outputParameterError", 
     "不能正确地设置存储过程所需要的输出参数，可能是参数的类型不正确或者参数的个数不一致。请检查存储过程：" }, 
     { "jdbcConnection.callableStatement.executeError", 
     "不能正确地执行目标存储过程，可能是存储过程内部的SQL语句有错误或者调用存储过程的参数错误。请检查存储过程：" }, 
     { "jdbcConnection.callableStatement.getOutputParameterError", 
     "执行存储过程后，不能正确地获得返回的输出参数，请检查存储过程：" }, 
     { "jdbcConnection.callableStatement.resultSetError", 
     "执行存储过程后，不能正确地获得返回的结果集，请检查存储过程：" }, 
     { "jdbcConnection.divPageAllPO.checkWhereString", 
     "请检查分页调用中的数据库表名称和查询的条件字符串是否正确，目标数据库表名：" }, 
     { "jdbcConnection.divPageAllPO.prepareStatementError", 
     "不能正确地创建出分页查询的PreparedStatement语句对象，可能是所要调用的数据库表名称或者查询条件字符串不正确，目标数据库表名：" }, 
     { "jdbcConnection.divPageAllPO.executePrepareStatementError", 
     "不能正确地执行分页查询的PreparedStatement语句对象，可能是所要调用的数据库表名称或者查询条件字符串不正确，目标数据库表名：" }, 
     { "jdbcConnection.divPageAllPO.nextResultError", 
     "正确地执行分页查询的PreparedStatement语句对象，不能移动结果集的指针。可能是没有获得满足查询条件的结果集数据，目标数据库表名：" }, 
     { "jdbcConnection.queryAllPO.prepareStatementError", 
     "不能正确地创建出查询功能的PreparedStatement语句对象，可能是所要调用的数据库表名称或者查询条件字符串不正确，目标数据库表名：" }, 
     { "jdbcConnection.insertOnePO.prepareStatementError", 
     "不能正确地创建出插入功能的PreparedStatement语句对象，可能是所要调用的数据库表名称或者插入的参数不正确，目标数据库表名：" }, 
     { "jdbcConnection.updateOnePO.prepareStatementError", 
     "不能正确地创建出修改功能的PreparedStatement语句对象，可能是所要调用的数据库表名称或者修改的参数不正确，目标数据库表名：" }, 
     { "jdbcConnection.deleteOnePO.prepareStatementError", 
     "不能正确地创建出删除功能的PreparedStatement语句对象，可能是所要调用的数据库表名称或者删除的参数不正确，目标数据库表名：" }, 
     { "jdbcConnection.dropTable.prepareStatementError", 
     "不能正确地创建出删除数据库表功能的PreparedStatement语句对象，可能是相关的sQL语句不正确，目标SQL语句为：" }, 
     { "jdbcConnection.dropTable.executeError", 
     "不能正确地执行删除数据库表功能的PreparedStatement语句对象，可能是相关的sQL语句不正确，目标SQL语句为：" }, 
     { "jdbcConnection.queryAllPO.executePrepareStatementError", 
     "不能正确地执行查询功能的PreparedStatement语句对象，可能是所要调用的数据库表名称或者查询条件字符串不正确，目标数据库表名：" }, 
     { "jdbcConnection.queryAllPO.nextResultError", 
     "正确地执行查询功能的PreparedStatement语句对象，不能移动结果集的指针。可能是没有获得满足查询条件的结果集数据，目标数据库表名：" }, 
     { "jdbcConnection.databaseMetaData.getMetaDataError", 
     "不能正确地获得描述数据库状态信息的DatabaseMetaData对象，目标数据库表名：" }, 
     { "jdbcConnection.databaseMetaData.getColumnCountError", 
     "不能正确地从描述数据库状态信息的DatabaseMetaData对象中获得当前的字段总数量，目标数据库表名：" }, 
     { "jdbcConnection.databaseMetaData.getColumnTypeError", 
     "不能正确地从描述数据库状态信息的DatabaseMetaData对象中获得当前的字段类型信息，目标数据库表名：" }, 
     { "jdbcConnection.databaseMetaData.primaryKeyResultSetError", 
     "不能正确地获得描述数据库表主键状态信息，目标数据库表名：" }, 
     { "jdbcConnection.queryStatement.parameterError", 
     "不能正确地设置查询SQL语句所需要的输入调用参数，可能是参数的类型不正确或者参数的个数不一致。目标数据库表名：" }, 
     { "jdbcConnection.updateOnePO.parameterError", 
     "不能正确地设置修改类的SQL语句中所需要的输入调用参数，可能是参数的类型不正确或者参数的个数不一致。目标数据库表名：" }, 
     { "IllegalArgumentExceptionError", 
     "在调用系统中的某个方法时，传递了不合法或不正确的参数值。原始的异常错误信息如下：" }, 
     { "IllegalAccessException", 
     "对不允许调用的方法进行了强制调用，如强制对类中的private类型的方法进行调用。原始的异常错误信息如下：" }, 
     { "jdbcConnection.insertOnePOByPrimaryKey.executePrepareStatementError", 
     "不能正确地执行对数据库表中的数据插入操作，可能是插入的数据不正确或者数据库表名称不正确，目标数据库表名：" }, 
     { "jdbcConnection.updateOnePO.executePrepareStatementError", 
     "不能正确地执行对数据库表中的数据的修改操作，可能是提供的参数不正确或者数据库表名称不正确，目标数据库表名：" }, 
     { "jdbcConnection.deleteOnePO.executePrepareStatementError", 
     "不能正确地执行对数据库表中的数据的删除操作，可能是提供的参数不正确或者数据库表名称不正确，目标数据库表名：" }, 
     { "jdbcConnection.updateOnePO.rollbackError", 
     "在批量修改数据时不能正确地执行回滚动恢复操作，修改操作的SQL语句为：" }, 
     { "jdbcConnection.updateOnePO.executeBatchError", 
     "在批量修改数据时不能正确地执行修改操作，可能是修改功能的SQL语句不正确，修改操作的SQL语句为：" }, 
     { "common.connectionPool.driverClassName", 
     "在创建CommonDaoBean的数据连接池时不能正确地加载JDBC驱动程序，可能是提供的类名不正确或者没有在classPath环境中添加目标驱动程序Jar包文件。目标驱动程序类名称为：" }, 
     { "common.connectionPool.createJDBCConnection", 
     "在创建CommonDaoBean的数据连接池时不能正确地创建出JDBC数据库连接对象，可能是数据库服务器没有启动或者所提供的数据库连接参数不正确请确认数据库服务器启动或者提供正确的连接参数。" } };
 
   protected Object[][] getContents()
   {
     return exceptionInfoContents;
   }
 }

